/******************************************************************/
/*   10/01/96  (merja01)  - Added httpd user for ICE testing    **/
/*   05/05/99  (popri01)  - Added "drop"s for all users         **/
/******************************************************************/
CREATE USER "delim USER" WITH
  NOGROUP,
  PRIVILEGES=(CREATEDB,TRACE,MAINTAIN_LOCATIONS,OPERATOR),
  DEFAULT_PRIVILEGES=(CREATEDB,TRACE,MAINTAIN_LOCATIONS,OPERATOR),
  NOEXPIRE_DATE,
  NOPROFILE,
  NOSECURITY_AUDIT;
\go
DROP USER ingres;
\go
CREATE USER ingres WITH
  NOGROUP,
  PRIVILEGES=(CREATEDB,TRACE,SECURITY,MAINTAIN_LOCATIONS,OPERATOR,AUDITOR,MAINTAIN_AUDIT,MAINTAIN_USERS),
  DEFAULT_PRIVILEGES=(CREATEDB,TRACE,SECURITY,MAINTAIN_LOCATIONS,OPERATOR,AUDITOR,MAINTAIN_AUDIT,MAINTAIN_USERS),
  NOEXPIRE_DATE,
  NOPROFILE,
  NOSECURITY_AUDIT;
\go
DROP USER pvusr1;
\go
CREATE USER pvusr1 WITH
  NOGROUP,
  PRIVILEGES=(CREATEDB,TRACE,MAINTAIN_LOCATIONS,OPERATOR),
  DEFAULT_PRIVILEGES=(CREATEDB,TRACE,MAINTAIN_LOCATIONS,OPERATOR),
  NOEXPIRE_DATE,
  NOPROFILE,
  NOSECURITY_AUDIT;
\go
DROP USER pvusr2;
\go
CREATE USER pvusr2 WITH
  NOGROUP,
  PRIVILEGES=(CREATEDB,TRACE,MAINTAIN_LOCATIONS,OPERATOR),
  DEFAULT_PRIVILEGES=(CREATEDB,TRACE,MAINTAIN_LOCATIONS,OPERATOR),
  NOEXPIRE_DATE,
  NOPROFILE,
  NOSECURITY_AUDIT;
\go
DROP USER pvusr3;
\go
CREATE USER pvusr3 WITH
  NOGROUP,
  PRIVILEGES=(CREATEDB,TRACE,MAINTAIN_LOCATIONS,OPERATOR),
  DEFAULT_PRIVILEGES=(CREATEDB,TRACE,MAINTAIN_LOCATIONS,OPERATOR),
  NOEXPIRE_DATE,
  NOPROFILE,
  NOSECURITY_AUDIT;
\go
DROP USER pvusr4;
\go
CREATE USER pvusr4 WITH
  NOGROUP,
  PRIVILEGES=(CREATEDB,TRACE,MAINTAIN_LOCATIONS,OPERATOR),
  DEFAULT_PRIVILEGES=(CREATEDB,TRACE,MAINTAIN_LOCATIONS,OPERATOR),
  NOEXPIRE_DATE,
  NOPROFILE,
  NOSECURITY_AUDIT;
\go
DROP USER qatest;
\go
CREATE USER qatest WITH
  NOGROUP,
  PRIVILEGES=(CREATEDB,TRACE,MAINTAIN_LOCATIONS,OPERATOR),
  DEFAULT_PRIVILEGES=(CREATEDB,TRACE,MAINTAIN_LOCATIONS,OPERATOR),
  NOEXPIRE_DATE,
  NOPROFILE,
  NOSECURITY_AUDIT;
\go
DROP USER root;
\go
CREATE USER root WITH
  NOGROUP,
  PRIVILEGES=(CREATEDB,TRACE,SECURITY,MAINTAIN_LOCATIONS,OPERATOR,AUDITOR,MAINTAIN_AUDIT,MAINTAIN_USERS),
  DEFAULT_PRIVILEGES=(CREATEDB,TRACE,SECURITY,MAINTAIN_LOCATIONS,OPERATOR,AUDITOR,MAINTAIN_AUDIT,MAINTAIN_USERS),
  NOEXPIRE_DATE,
  NOPROFILE,
  NOSECURITY_AUDIT;
\go
DROP USER "seLEct";
\go
CREATE USER "seLEct" WITH
  NOGROUP,
  PRIVILEGES=(CREATEDB,TRACE,MAINTAIN_LOCATIONS,OPERATOR),
  DEFAULT_PRIVILEGES=(CREATEDB,TRACE,MAINTAIN_LOCATIONS,OPERATOR),
  NOEXPIRE_DATE,
  NOPROFILE,
  NOSECURITY_AUDIT;
\go
DROP USER testenv;
\go
CREATE USER testenv WITH
  NOGROUP,
  PRIVILEGES=(CREATEDB,TRACE,SECURITY,MAINTAIN_LOCATIONS,OPERATOR,AUDITOR,MAINTAIN_AUDIT,MAINTAIN_USERS),
  DEFAULT_PRIVILEGES=(CREATEDB,TRACE,SECURITY,MAINTAIN_LOCATIONS,OPERATOR,AUDITOR,MAINTAIN_AUDIT,MAINTAIN_USERS),
  NOEXPIRE_DATE,
  NOPROFILE,
  NOSECURITY_AUDIT;
\go
DROP USER u65A;
\go
CREATE USER u65A WITH
  NOGROUP,
  PRIVILEGES=(CREATEDB,TRACE,MAINTAIN_LOCATIONS,OPERATOR),
  DEFAULT_PRIVILEGES=(CREATEDB,TRACE,MAINTAIN_LOCATIONS,OPERATOR),
  NOEXPIRE_DATE,
  NOPROFILE,
  NOSECURITY_AUDIT;
\go
DROP USER u65B;
\go
CREATE USER u65B WITH
  NOGROUP,
  PRIVILEGES=(CREATEDB,TRACE,MAINTAIN_LOCATIONS,OPERATOR),
  DEFAULT_PRIVILEGES=(CREATEDB,TRACE,MAINTAIN_LOCATIONS,OPERATOR),
  NOEXPIRE_DATE,
  NOPROFILE,
  NOSECURITY_AUDIT;
\go
DROP USER u65C;
\go
CREATE USER u65C WITH
  NOGROUP,
  PRIVILEGES=(CREATEDB,TRACE,MAINTAIN_LOCATIONS,OPERATOR),
  DEFAULT_PRIVILEGES=(CREATEDB,TRACE,MAINTAIN_LOCATIONS,OPERATOR),
  NOEXPIRE_DATE,
  NOPROFILE,
  NOSECURITY_AUDIT;
\go
DROP USER u65D;
\go
CREATE USER u65D WITH
  NOGROUP,
  PRIVILEGES=(CREATEDB,TRACE,MAINTAIN_LOCATIONS,OPERATOR),
  DEFAULT_PRIVILEGES=(CREATEDB,TRACE,MAINTAIN_LOCATIONS,OPERATOR),
  NOEXPIRE_DATE,
  NOPROFILE,
  NOSECURITY_AUDIT;
\go
DROP USER u65E;
\go
CREATE USER u65E WITH
  NOGROUP,
  PRIVILEGES=(CREATEDB,TRACE,MAINTAIN_LOCATIONS,OPERATOR),
  DEFAULT_PRIVILEGES=(CREATEDB,TRACE,MAINTAIN_LOCATIONS,OPERATOR),
  NOEXPIRE_DATE,
  NOPROFILE,
  NOSECURITY_AUDIT;
\go
DROP USER httpd;
\go
CREATE USER httpd WITH
  NOGROUP,
  PRIVILEGES=(CREATEDB,TRACE,SECURITY,MAINTAIN_LOCATIONS,OPERATOR),
  DEFAULT_PRIVILEGES=(CREATEDB,TRACE,MAINTAIN_LOCATIONS,OPERATOR),
  NOEXPIRE_DATE,
  NOPROFILE,
  NOSECURITY_AUDIT;
\go
DROP USER notauth;
\go
DROP USER super;
\go
DROP USER syscat;
\go
